export const ADD_POKEMON = "ADD_POKEMON";
export const UPDATE_POKEMON = "UPDATE_POKEMON";
export const REMOVE_POKEMON = "REMOVE_POKEMON";
export const ADD_POKEMON_TO_TEAM = "ADD_POKEMON_TO_TEAM";
export const REMOVE_POKEMON_FROM_TEAM = "REMOVE_POKEMON_FROM_TEAM";
export const ADD_TO_POKEBAG = "ADD_TO_INVENTORY";
export const REMOVE_FROM_POKEBAG = "REMOVE_FROM_INVENTORY";


